version: '3.3'

services:
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./db-volume:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
#    ulimits:
#      nproc: 400
#    deploy:
#      resources:
#        limits:
#          memory: "512m"
#          cpus: 0.2
  web:
    build: .
    depends_on:
      - mysql
    ports:
      - '8000:80'
#    volumes:
#      - ./src:/var/www/html
#      - ./templates:/var/www/templates
#    ulimits:
#      nproc: 400
#    deploy:
#      resources:
#        limits:
#          memory: "512m"
#          cpus: 0.2
