
version: "3"

services:
  redis:
    restart: always
    image: redis:alpine
    volumes:
      - .data/redis:/data

  shop:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - 0.0.0.0:42069:42069
