version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_db
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
  web:
    build: web/
    restart: always
    ports:
      - 5000:5000
    expose:
      - "5000"
    depends_on:
      - db
    links:
      - db
    env_file:
      - ctfzone.env
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G

  admin:
    build: admin/
    depends_on:
      - web
    links:
      - web
    env_file:
      - ctfzone.env

