version: '3'

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: bartender
      MYSQL_PASSWORD: bottle_of_whiskey_plz
      MYSQL_DATABASE: winner-bar
      MYSQL_ROOT_PASSWORD: who_pays_that_wins
    ports:
      - "3306"
    restart: on-failure

  web:
    build: ./src
    depends_on:
      - mysql
    volumes:
      - ./src:/src
    ports:
      - "777:777"
    command: /bin/bash ./entrypoint.sh
    restart: on-failure
